services:
  app:
    build:
      context: ./dist
      dockerfile: Dockerfile
    container_name: rhino-bond-dashboard
    ports:
      - 8080:80

  nginx:
    image: nginx:alpine
    container_name: rhino-bond-dashboard
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app

